---
title: "TrLab experiment report: all_003"
output: 
  pdf_document:
      toc: true
---

\newpage

```{r, environment, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE , warning = FALSE , results = "asis")
source("load_environment.R", local = knitr::knit_global())
source("./utils/triq_management.R", local = knitr::knit_global())
source("./utils/experiment_management.R", local = knitr::knit_global())
# Set the experiment .sol absolute path
solPath <- "/Users/davgutavi/triclustering_france/all_003/all_003.sol"
# Load experiment
experiment <- loadExperiment(solPath)
```

\section{TRIQ analysis}
\Large

```{r, triq}
# Load TRIQ analysis
triq_data <- load_triq_values(solPath,experiment$dataset_info$.attrs[14])
rounded_triq_data <- round_triq_data(triq_data)

cat(paste0("Best solution found: Solution ",rounded_triq_data$best_tricluster_id,"\n\n"))
cat(paste0("Best TRIQ value: ",rounded_triq_data$best_triq_value,"\n\n"))
cat(paste0("TRIQ mean: ",rounded_triq_data$triq_mean,"\n\n"))
cat(paste0("TRIQ stdev: ",rounded_triq_data$triq_stdev,"\n\n"))
triq_table <- get_triq_table(rounded_triq_data$triq_solutions)

# Print table
knitr::kable(triq_table)
```

\section{Graphical analysis}

```{r, graphs,fig.width = 8, fig.height=9, fig.align='center'}

# Build pattern graphs
patternGraphs <- buildExperimentPatternGraphs(experiment,
  value_tag = "consumption",
  layer_tag = "year",
  instance_tag = "time slot",
  ial_title = "",
  ila_title = "",
  lia_title = "")


i <- 1
for (sol_gr in patternGraphs){
  cat(paste0("\\subsection{Solution " , i, "}\n\n"))
  cat(paste0("\\subsubsection{Monthly consumption series for each year for Solution ",i,"}\n\n"))
  print(sol_gr$ial)
  cat("\n\n")
  cat(paste0("\\subsubsection{Yearly consumption series for each month for Solution ",i,"}\n\n"))
  print(sol_gr$ila)
  cat("\n\n")
  cat(paste0("\\subsubsection{Annual consumption for each month for Solution ",i,"}\n\n"))
  print(sol_gr$lia)
  cat("\n\n")
  i <- i+1
}
```
