# From Bioconductor
if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("GEOquery")
BiocManager::install("affy")
install.packages("rmarkdown")
install.packages("shinythemes")
install.packages("shinyFiles")
install.packages("knitr")
install.packages("rentrez")
install.packages("tidyverse")
install.packages("xml2")
install.packages("ggplot2")
install.packages("reshape")
install.packages("gridExtra")
install.packages("DT")
install.packages("glue")
install.packages("lattice")
install.packages("grid")
install.packages("stringr")
install.packages("usefun")
install.packages("dplyr")
install.packages("kableExtra")
# *****
install.packages("rgl")
install.packages("reshape2")
install.packages("modeest")
