install.packages("rmarkdown")
install.packages("shinythemes")
install.packages("shinyFiles")
install.packages("knitr")
install.packages("rentrez")
install.packages("tidyverse")
install.packages("xml2")
install.packages("ggplot2")
install.packages("reshape")
install.packages("gridExtra")
install.packages("DT")
install.packages("glue")
install.packages("lattice")
install.packages("grid")
install.packages("stringr")
install.packages("usefun")
install.packages("dplyr")
install.packages("kableExtra")
# *****
install.packages("rgl")
install.packages("reshape2")
install.packages("modeest")
install.packages("xtable")
# *****
install.packages("extrafont")
library(extrafont)
font_import()
loadfonts()

# From Bioconductor
if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("GEOquery")
BiocManager::install("affy")
BiocManager::install("biomaRt")
BiocManager::install("hgu219.db")
BiocManager::install("rae230a.db")

# Optional packages 
install.packages("tictoc")
